from sqlalchemy import Column, Integer, String, Text, DateTime, Date, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Property(Base):
    __tablename__ = "properties"

    propertyid = Column(Integer, primary_key=True, autoincrement=True)
    propertyname = Column(String(100), nullable=False)
    email = Column(String(35), nullable=False)
    phone = Column(String(15), nullable=False)
    status = Column(String(1), nullable=False)
    add1 = Column(String(100), nullable=False)
    add2 = Column(String(20), nullable=False)
    city = Column(String(20), nullable=False)
    state = Column(String(20), nullable=False)
    country = Column(String(3), nullable=False)
    postcode = Column(String(10), nullable=False)
    createdon = Column(DateTime, nullable=False)
    updatedon = Column(DateTime, nullable=False)
    hkcharge = Column(Integer, nullable=False)
    spacno = Column(String(20), nullable=False)
    billday = Column(Integer, nullable=False)
    dueday = Column(Integer, nullable=False)
    roomtype = Column(String(50), nullable=False)
    ppname = Column(String(100), nullable=False)
    ppaddress = Column(String(200), nullable=False)
    propertytype = Column(String(50), nullable=False)
    visitorspolicy = Column(String(50), nullable=False)
    petspolicy = Column(String(50), nullable=False)
    commontv = Column(String(5), nullable=False)
    wifi = Column(String(5), nullable=False)
    diningtable = Column(String(5), nullable=False)
    sofa = Column(String(5), nullable=False)
    fridge = Column(String(5), nullable=False)
    washer = Column(String(5), nullable=False)
    dryer = Column(String(5), nullable=False)
    gym = Column(String(5), nullable=False)
    swimming = Column(String(5), nullable=False)
    tenniscourt = Column(String(5), nullable=False)
    badminton = Column(String(5), nullable=False)
    golfdrive = Column(String(5), nullable=False)
    squashcourt = Column(String(5), nullable=False)
    futasal = Column(String(5), nullable=False)
    nearestmrt = Column(String(300), nullable=False)
    nearestsupermarket = Column(String(150), nullable=False)
    nearestfoodcourt = Column(String(150), nullable=False)
    description = Column(Text, nullable=False)
    microwave = Column(String(5), nullable=False)
    nearestbusstop = Column(String(50), nullable=False)
    company = Column(Integer, nullable=False)
    agent = Column(Integer, nullable=False)
    owner = Column(Integer, nullable=False)
    profileimg = Column(String(50), nullable=False)
    propmanager = Column(Integer, nullable=False)
    beneficiary = Column(String(30), nullable=False)
    bankname = Column(String(30), nullable=False)
    swiftcode = Column(String(30), nullable=False)
    accountnumber = Column(String(30), nullable=False)
    mrt = Column(String(300), nullable=False)
    buildingname = Column(String(100), nullable=False)
    level = Column(Integer, nullable=False)
    levelna = Column(String(5), nullable=False)
    unit = Column(Integer, nullable=False)
    unitna = Column(String(5), nullable=False)
    zone = Column(String(7), nullable=False)
    district = Column(Integer, nullable=False)
    coverage = Column(String(100), nullable=False)
    accesscode = Column(String(50), nullable=False)
    wifiname1 = Column(String(50), nullable=False)
    wifiname2 = Column(String(50), nullable=False)
    wifipassword = Column(String(50), nullable=False)
    ian = Column(String(50), nullable=False)
    gastype = Column(String(10), nullable=False)
    gplate = Column(String(3), nullable=False)
    eretailer = Column(String(30), nullable=False)
    workplaces = Column(String(500), nullable=False)

    rooms = relationship("Room", back_populates="property")
    washrooms = relationship("Washroom", back_populates="property")


class Room(Base):
    __tablename__ = 'rooms'

    roomid = Column(Integer, primary_key=True, autoincrement=True)
    propertyid = Column(Integer, ForeignKey('properties.propertyid'), nullable=False)
    roomnumber = Column(String(15), nullable=False)
    roomtype = Column(String(50), nullable=False)
    status = Column(String(1), nullable=False)
    createdon = Column(Date, nullable=False)
    updatedon = Column(DateTime, nullable=False)
    roomlink = Column(String(250), nullable=False)
    notes = Column(Text, nullable=False)
    ppname = Column(String(100), nullable=False)
    ppaddress = Column(String(100), nullable=False)
    propertytype = Column(String(50), nullable=False)
    eavaildate = Column(Date, nullable=False)
    environment = Column(String(100), nullable=False)
    visitorspolicy = Column(String(50), nullable=False)
    petspolicy = Column(String(50), nullable=False)
    maxoccupancy = Column(String(50), nullable=False)
    ptenanttype = Column(String(50), nullable=False)
    kingsizebed = Column(String(50), nullable=False)
    queensizebed = Column(String(5), nullable=False)
    wardrobe = Column(String(5), nullable=False)
    sidetable = Column(String(5), nullable=False)
    aircon = Column(String(5), nullable=False)
    fan = Column(String(5), nullable=False)
    studytable = Column(String(5), nullable=False)
    kettle = Column(String(5), nullable=False)
    tv = Column(String(5), nullable=False)
    airpurifier = Column(String(5), nullable=False)
    window = Column(String(5), nullable=False)
    usagetype = Column(String(50), nullable=False)
    commontv = Column(String(5), nullable=False)
    wifi = Column(String(5), nullable=False)
    diningtable = Column(String(5), nullable=False)
    sofa = Column(String(5), nullable=False)
    fridge = Column(String(5), nullable=False)
    washer = Column(String(5), nullable=False)
    dryer = Column(String(5), nullable=False)
    gym = Column(String(5), nullable=False)
    swimming = Column(String(5), nullable=False)
    tenniscourt = Column(String(5), nullable=False)
    badminton = Column(String(5), nullable=False)
    golfdrive = Column(String(5), nullable=False)
    squashcourt = Column(String(5), nullable=False)
    futasal = Column(String(5), nullable=False)
    nearestmrt = Column(String(50), nullable=False)
    nearestbusstop = Column(String(50), nullable=False)
    nearestsupermarket = Column(String(150), nullable=False)
    nearestfoodcourt = Column(String(150), nullable=False)
    published = Column(String(1), nullable=False)
    description = Column(Text, nullable=False)
    cpersonname = Column(String(50), nullable=False)
    cpersonphone = Column(String(15), nullable=False)
    cpersonwhatsapp = Column(String(15), nullable=False)
    cpersonemail = Column(String(100), nullable=False)
    singlebed = Column(String(5), nullable=False)
    onlymattress = Column(String(5), nullable=False)
    ventilator = Column(String(5), nullable=False)
    supersinglebed = Column(String(5), nullable=False)
    microwave = Column(String(5), nullable=False)
    occupancystatus = Column(String(35), nullable=False)
    ptwd = Column(String(10), nullable=False)
    ptwe = Column(String(10), nullable=False)
    agents = Column(String(200), nullable=False)
    sellingprice = Column(Integer, nullable=False)
    title = Column(String(100), nullable=False)
    airconditioned = Column(String(3), nullable=False, default='No')
    rentmonth = Column(Integer, nullable=False)
    commonexpenses = Column(String(10), nullable=False)
    marketingstatus = Column(String(30), nullable=False)

    property = relationship("Property", back_populates="rooms")


class Washroom(Base):
    __tablename__ = 'washrooms'

    id = Column(Integer, primary_key=True, autoincrement=True)
    propertyid = Column(Integer, ForeignKey('properties.propertyid'), nullable=False)
    washroomno = Column(String(10), nullable=False)
    size = Column(String(10), nullable=False)
    bathtub = Column(String(3), nullable=False)
    location = Column(String(15), nullable=False)
    bidetspray = Column(String(3), nullable=False)
    totalusers = Column(Integer, nullable=False)
    usedrooms = Column(String(20), nullable=False)
    createdon = Column(DateTime, nullable=False)
    updatedon = Column(DateTime, nullable=False)

    property = relationship("Property", back_populates="washrooms")
